name: R Script Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("showtext")'

      - name: Run R script
        run: |
          Rscript Script.R  # Remplacez par le chemin vers votre script
