name: Daily R Script Execution

# Déclenche le workflow quotidiennement à 8h du matin (UTC)
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: Install R packages
        run: |
          install.packages(c("tidyverse", "showtext"))

      - name: Execute R script
        run: |
          Rscript Script.R
